path_tolerance: 0.005
resample_dt: 0.02
min_angle_change: 0.001

default_workspace_bounds: 2.0
start_state_max_bounds_error: 0.01
start_state_max_dt: 10.0
jiggle_fraction: 0.005
max_sampling_attempts: 500

goal_orientation_tolerance: 0.001
goal_position_tolerance: 0.005
planning_time: 5.0

longest_valid_segment_fraction: 0.01   # or smaller

planning_plugin: ompl_interface/OMPLPlanner
planning_plugins:
  - ompl_interface/OMPLPlanner
request_adapters:
  - default_planning_request_adapters/ResolveConstraintFrames
  - default_planning_request_adapters/ValidateWorkspaceBounds
  - default_planning_request_adapters/CheckStartStateBounds
  - default_planning_request_adapters/CheckStartStateCollision
response_adapters:
  - default_planning_response_adapters/AddTimeOptimalParameterization
  - default_planning_response_adapters/ValidateSolution
  - default_planning_response_adapters/DisplayMotionPath

planner_configs:
  RRTConnectkConfigDefault:
    type: geometric::RRTConnect
    range: 0.1    # Max motion added to tree. ==> maxDistance_ default: 0.0, if 0.0, set on setup()
    # longest_valid_segment_fraction: 0.01   # or smaller
    maximum_waypoint_distance: 0.005
    enforce_joint_state_space: true
    # enforce_constrained_state_space: true
    # projection_evaluator: link(fr3_hand_tcp)

  RRTstarkConfigDefault:
    type: geometric::RRTstar
    range: 0.01  # Max motion added to tree. ==> maxDistance_ default: 0.0, if 0.0, set on setup()
    goal_bias: 0.05  # When close to goal select goal, with this probability? default: 0.05
    delay_collision_checking: 1  # Stop collision checking as soon as C-free parent found. default 1
    maximum_waypoint_distance: 0.005

fr3_arm:
  enforce_constrained_state_space: true
  projection_evaluator: link(fr3_hand_tcp)
  planner_configs:
    - RRTstarkConfigDefault
    - RRTConnectkConfigDefault
fr3_hand:
  planner_configs:
    - RRTstarkConfigDefault
    - RRTConnectkConfigDefault