geometry_msgs/Pose grasp_pose
float32 goal_x
float32 goal_y
float32 goal_z
int64 target_id
---
bool success
bool is_valid
float32 score
int64 err_code
string message
string err_source
string err_message
float32 pickup_plan_time
float32 pickup_ik_time
float32 pickup_refine_time
float32 move_plan_time
float32 move_ik_time
float32 move_refine_time
---
string progress