z_coords_min: 0.001
z_coords_max: 100.0
x_grasp_min: -1.0
x_grasp_max: 1.0
y_grasp_min: -1.0
y_grasp_max: 1.0
z_grasp_min: 0.05
z_grasp_max: 0.5

apply_object_mask: False
apply_collisions: True
dense_grasp: True
top_down_grasp: False

min_grasp_width: 0.0
max_grasp_pitch_roll_deg: 5.0

nms_translation_thresh: 0.01
nms_angle_thresh_deg: 5.0

grasp_z_offset: 0.0
grasp_axis_offset: 0.001

max_gripper_width: 0.1
gripper_height: 0.03
mask_radius: 0.08

symmetry_enable: True
symmetry_layer_height: 0.03
symmetry_rotation_step: 45
symmetry_similarity_threshold: 0.01

no_rgb: True
pointcloud_topic: "/octomap_point_cloud_centers"
visualise: True
save_data: True

enable_grasp_selection: True

pointcloud_from_file: True
pointcloud_file: "/ros2_ws/src/pointclouds/beaker_lrg.npz"