z_coords_min: 0.001
z_coords_max: 2.0
x_grasp_min: -1.0
x_grasp_max: 1.0
y_grasp_min: -1.0
y_grasp_max: 1.0
z_grasp_min: 0.05
z_grasp_max: 0.5

apply_object_mask: False
apply_collisions: True
dense_grasp: True
top_down_grasp: False

min_grasp_width: 0.0
max_grasp_pitch_roll_deg: 5.0

nms_translation_thresh: 0.01
nms_angle_thresh_deg: 5.0

grasp_z_offset: 0.0
grasp_axis_offset: -0.02

max_gripper_width: 0.1
gripper_height: 0.03
mask_radius: 0.08

# symmetry_enable: False
symmetry_enable: True
symmetry_layer_height: 0.03
symmetry_rotation_step: 45
symmetry_similarity_threshold: 0.01

no_rgb: True
pointcloud_topic: "/octomap_point_cloud_centers"
save_data: True

plot_selection_graphs: True
planning_time_multiplier: 2.0
acquisition_kappa: 3.0
kernel_length_scale_z: 0.03
kernel_length_scale_th: 0.8
kernel_matern_nu: 2.5

# for normal stuff
baseline_planning_time: 0.5
total_planning_time_sec: 900
enable_grasp_selection: True
visualise: False

# for baseline stuff
# baseline_planning_time: 1.0
# total_planning_time_sec: 900
# enable_grasp_selection: False
# visualise: True


acquisition_eps: 0.1
acquisition_enable_decay: False
acquisition_eps_final: 0.1
acquisition_eps_decay_rate: 0.99

pointcloud_from_file: True
pointcloud_file: "/ros2_ws/src/pointclouds/beaker_lrg.npz"