objects:
  - conic_flask
  # - volumetric_flask
  # - round_bottomed_flask
  # - measuring_cylinder_sml
  # - measuring_cylinder_lrg
  # - beaker_sml
  # - beaker_med
  # - beaker_lrg
  - table
  # - beaker_lrg_obstacle_0
  # - beaker_lrg_obstacle_1
  # - beaker_lrg_obstacle_3
  # - beaker_lrg_obstacle_4
  # - beaker_lrg_obstacle_6
  # - beaker_lrg_obstacle_7
  # - beaker_lrg_obstacle_8
  # - beaker_lrg_obstacle_9
  # - tall_obstacle_5
  # - tall_obstacle_6
  # - tall_obstacle_7

table:
  object_id: 99
  geometry_file: "table.sdf"
  x: 0.3
  y: -0.3
  z: 0.1
  primitive_type: BOX
  primitive_dims:
    x: 0.3
    y: 0.3 
    z: 0.2

conic_flask:
  object_id: 0
  geometry_file: "conic_flask.sdf"
  x: 0.3
  y: 0.0
  z: 0.03
  primitive_type: MESH
  primitive_dims:
    file: "package://hts_robotics/objects/meshes/Conic_Flask_Measured_Low_Fidelity_mm.stl"

volumetric_flask:
  object_id: 1
  geometry_file: "volumetric_flask.sdf"
  x: 0.3
  y: 0.0
  z: 0.03
  primitive_type: MESH
  primitive_dims:
    file: "package://hts_robotics/objects/meshes/Volumetric_Flask_Measured_Low_Fidelity_mm.stl"

round_bottomed_flask:
  object_id: 2
  geometry_file: "round_bottomed_flask.sdf"
  x: 0.3
  y: 0.0
  z: 0.03
  primitive_type: MESH
  primitive_dims:
    file: "package://hts_robotics/objects/meshes/Round_Flask_Measured_Low_Fidelity_mm.stl"

beaker_sml:
  object_id: 3
  geometry_file: "beaker_small.sdf"
  x: 0.3
  y: 0.0
  z: 0.03
  primitive_type: MESH
  primitive_dims:
    file: "package://hts_robotics/objects/meshes/Beaker_Small_Low_Fidelity_mm.stl"

beaker_med:
  object_id: 4
  geometry_file: "beaker_medium.sdf"
  x: 0.3
  y: 0.0
  z: 0.03
  primitive_type: MESH
  primitive_dims:
    file: "package://hts_robotics/objects/meshes/Beaker_Medium_Low_Fidelity_mm.stl"

beaker_lrg:
  object_id: 5
  geometry_file: "beaker_large.sdf"
  x: 0.3
  y: 0.0
  z: 0.03
  primitive_type: MESH
  primitive_dims:
    file: "package://hts_robotics/objects/meshes/Beaker_Large_Low_Fidelity_mm.stl"
  
measuring_cylinder_sml:
  object_id: 6
  geometry_file: "measuring_cylinder_small.sdf"
  x: 0.3
  y: 0.0
  z: 0.03
  primitive_type: MESH
  primitive_dims:
    file: "package://hts_robotics/objects/meshes/Measuring_Cylinder_Small_Low_Fidelity_mm.stl"

measuring_cylinder_lrg:
  object_id: 7
  geometry_file: "measuring_cylinder_large.sdf"
  x: 0.3
  y: 0.0
  z: 0.03
  primitive_type: MESH
  primitive_dims:
    file: "package://hts_robotics/objects/meshes/Measuring_Cylinder_Large_Low_Fidelity_mm.stl"

beaker_lrg_obstacle_0:
  object_id: 80
  geometry_file: "beaker_large.sdf"
  x: -0.3
  y: 0.7
  z: 0.03
  primitive_type: MESH
  primitive_dims:
    file: "package://hts_robotics/objects/meshes/Beaker_Large_Low_Fidelity_mm.stl"

beaker_lrg_obstacle_1:
  object_id: 81
  geometry_file: "beaker_large.sdf"
  x: -0.2
  y: 0.6
  z: 0.03
  primitive_type: MESH
  primitive_dims:
    file: "package://hts_robotics/objects/meshes/Beaker_Large_Low_Fidelity_mm.stl"

beaker_lrg_obstacle_3:
  object_id: 83
  geometry_file: "beaker_large.sdf"
  x: 0.0
  y: 0.4
  z: 0.03
  primitive_type: MESH
  primitive_dims:
    file: "package://hts_robotics/objects/meshes/Beaker_Large_Low_Fidelity_mm.stl"
  
beaker_lrg_obstacle_4:
  object_id: 84
  geometry_file: "beaker_large.sdf"
  x: 0.1
  y: 0.3
  z: 0.03
  primitive_type: MESH
  primitive_dims:
    file: "package://hts_robotics/objects/meshes/Beaker_Large_Low_Fidelity_mm.stl"

beaker_lrg_obstacle_6:
  object_id: 86
  geometry_file: "beaker_large.sdf"
  x: 0.4
  y: 0.1
  z: 0.03
  primitive_type: MESH
  primitive_dims:
    file: "package://hts_robotics/objects/meshes/Beaker_Large_Low_Fidelity_mm.stl"

beaker_lrg_obstacle_7:
  object_id: 87
  geometry_file: "beaker_large.sdf"
  x: 0.5
  y: 0.2
  z: 0.03
  primitive_type: MESH
  primitive_dims:
    file: "package://hts_robotics/objects/meshes/Beaker_Large_Low_Fidelity_mm.stl"

beaker_lrg_obstacle_8:
  object_id: 88
  geometry_file: "beaker_large.sdf"
  x: 0.2
  y: -0.1
  z: 0.03
  primitive_type: MESH
  primitive_dims:
    file: "package://hts_robotics/objects/meshes/Beaker_Large_Low_Fidelity_mm.stl"
  
beaker_lrg_obstacle_9:
  object_id: 89
  geometry_file: "beaker_large.sdf"
  x: 0.1
  y: -0.2
  z: 0.03
  primitive_type: MESH
  primitive_dims:
    file: "package://hts_robotics/objects/meshes/Beaker_Large_Low_Fidelity_mm.stl"

tall_obstacle_5:
  object_id: 90
  geometry_file: "measuring_cylinder_large.sdf"
  x: 0.3
  y: 0.5
  z: 0.03
  primitive_type: MESH
  primitive_dims:
    file: "package://hts_robotics/objects/meshes/Measuring_Cylinder_Large_Low_Fidelity_mm.stl"

tall_obstacle_6:
  object_id: 91
  geometry_file: "measuring_cylinder_large.sdf"
  x: -0.4
  y: 0.2
  z: 0.03
  primitive_type: MESH
  primitive_dims:
    file: "package://hts_robotics/objects/meshes/Measuring_Cylinder_Large_Low_Fidelity_mm.stl"

tall_obstacle_7:
  object_id: 92
  geometry_file: "measuring_cylinder_large.sdf"
  x: 0.0
  y: -0.3
  z: 0.03
  primitive_type: MESH
  primitive_dims:
    file: "package://hts_robotics/objects/meshes/Measuring_Cylinder_Large_Low_Fidelity_mm.stl"